### ISSUE TITLE
Current bugs.

### ISSUE THREAD

**Issue by Derek1199** [d0k3/OpenFirmInstaller#1]
Currently the installer fails to actually install fastboot3DS. I tested this by compiling fastboot3DS, putting it inside the /ofi folder. And it said failed signature check, also, when booting into this installer. It says https://gitlab/d0k3/OpenFirmInstaller when it should be github instead of gitlab. Also, GodMode9 successfully does install fastboot3DS to firm0/firm1, ect. So it's not the firm signature. As verifying the firm, the firm has successful header, hash, and signature. And it works.

**Comment by d0k3** [comment]
fastboot3DS release builds are signed with a private key (not Nintendos). You don't have that private key, so fastboot3DS builds compiled by you lack that signature.

Before you ask - the key will not be released. It's a means of safety and makes sure no unauthorized fastboot3DS builds are installed via OFI or via the fastboot3DS updater.

**OFI will only install release builds of fastboot3DS**. Use GodMode9 for ones you compiled yourself.

**Comment by Derek1199** [comment]
Okay, good to know.
