### ISSUE TITLE
OpenFirmInstaller.3dsx does nothing

### ISSUE THREAD

**Issue by eku** [d0k3/OpenFirmInstaller#4]
The provided ```OpenFirmInstaller.3dsx``` from the release zip does nothing visible when started through the ```Homebrew Launcher```.

**Comment by d0k3** [comment]
Unsure what to do about that, and I'm pretty sure it's the same issue for SafeB9SInstaller, too. Maybe we will just remove that support, as there's little reason to use OpenFirmInstaller.3dsx from Homebrew Launcher nowadays. Let me know if you disagree, @eku.

**Comment by eku** [comment]
Yes, please remove the OpenFirmInstaller.3dsx completely and adapt the documentation.

**Comment by d0k3** [comment]
Okay, I thought about it. Yup, the .3DSX file will do nothing when launched from HB launcher on a current version system. However, if your 3DS is on a system version 9.0 and 9.2, the .3DSX file is a valid way of hacking your console.

You of course need Ninjhax, and of course there are much better and easier ways to do it nowadays. However, as this is still a valid way of installing the sighax FIRM, it will be kept in there. Closing this now.
